In [9]:
import numpy as np

#create shakespare words
words = ["thou", "art", "my", "help"]

#get wrds from dictionary
dictWords = ["my", "friend", "is", "thy", "God", "Zeus"]
dictWords.append(words)


lenDictWords = len(dictWords)
lenShakespare = len(words)

#one hot encoding 
np.zeros((lenShakespare,lenDictWords))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# Initialize the one-hot encoding matrix with zeros
one_hot_matrix = np.zeros((lenShakespare, lenDictWords))


# Fill in the matrix with 1s where there's a match
for i, word in enumerate(words):
    if word in dictWords:
        index = dictWords.index(word)
        one_hot_matrix[i][index] = 1

print(one_hot_matrix)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
# mdoel true dist
#assume uniform prior on K's
alphas = np.random.binomial(1, 1, size=lenDictWords)
K_Simplex = np.random.dirichlet(alphas) #give me

array([0.01125453, 0.00433121, 0.0332993 , 0.07626076, 0.1401756 ,
       0.27614527, 0.17446013, 0.06338885, 0.05097803, 0.16970631])